// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl1ybjojctRHRP_-EMV6N6pHQoDGs1kkM',
    appId: '1:577621665270:web:59a844c2939ebe7187d3d7',
    messagingSenderId: '577621665270',
    projectId: 'chatapp-10b57',
    authDomain: 'chatapp-10b57.firebaseapp.com',
    storageBucket: 'chatapp-10b57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM40awcSMPJ4K2AftH71FugIOfcKVkdvA',
    appId: '1:577621665270:android:46aa81f19be8148b87d3d7',
    messagingSenderId: '577621665270',
    projectId: 'chatapp-10b57',
    storageBucket: 'chatapp-10b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmaApsLRsXkKewRQqymr8fDsRW-PLy5o',
    appId: '1:577621665270:ios:9f3e0715cbaebcaf87d3d7',
    messagingSenderId: '577621665270',
    projectId: 'chatapp-10b57',
    storageBucket: 'chatapp-10b57.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmmaApsLRsXkKewRQqymr8fDsRW-PLy5o',
    appId: '1:577621665270:ios:9f3e0715cbaebcaf87d3d7',
    messagingSenderId: '577621665270',
    projectId: 'chatapp-10b57',
    storageBucket: 'chatapp-10b57.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl1ybjojctRHRP_-EMV6N6pHQoDGs1kkM',
    appId: '1:577621665270:web:10a80cd0c1b0d4ed87d3d7',
    messagingSenderId: '577621665270',
    projectId: 'chatapp-10b57',
    authDomain: 'chatapp-10b57.firebaseapp.com',
    storageBucket: 'chatapp-10b57.firebasestorage.app',
  );
}
